strains:
  proxy:
    url: https://proxy.primordialsoup.life
    origin: https://www.adobe.io/
  default:
    content: https://github.com/trieloff/helix-demo.git
    code: /trieloff/default/https---github-com-trieloff-helix-demo-git--master--
  legacy:
    url: https://www.primordialsoup.life/content
    origin: https://www.adobe.io    